#!/usr/bin/env bash
# Recursively scans the wallpaper directory and (re)generates GALLERY.md
# with a thumbnail grid, grouped by folder. Each thumbnail links to the
# image's blob view in the repo.

set -euo pipefail

repo_root="$(git rev-parse --show-toplevel)"
cd "$repo_root"

output="GALLERY.md"
search_dir="walls"
columns=4
thumb_width=200

ext_args=(-iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' -o -iname '*.gif' -o \
          -iname '*.bmp' -o -iname '*.tiff' -o -iname '*.tif' -o -iname '*.webp' -o \
          -iname '*.svg' -o -iname '*.avif')

mapfile -d '' -t all_images < <(find "$search_dir" -type f \( "${ext_args[@]}" \) -print0 | sort -z)
total=${#all_images[@]}

mapfile -t dirs < <(printf '%s\n' "${all_images[@]}" | xargs -r -I{} dirname {} | sort -u)

{
    echo "<!-- Auto-generated by .github/workflows/gallery.yml — do not edit by hand. -->"
    echo "# Wallpaper Gallery"
    echo
    echo "$total wallpaper(s) across ${#dirs[@]} folder(s). [⬅ Back to README](README.md)"

    for dir in "${dirs[@]}"; do
        echo
        echo "## $dir"
        echo
        echo "<table>"
        count=0
        while IFS= read -r -d '' img; do
            if (( count % columns == 0 )); then
                (( count > 0 )) && echo "</tr>"
                echo "<tr>"
            fi
            name="$(basename "$img")"
            printf '<td align="center"><a href="%s"><img src="%s" width="%d"/></a><br/><sub>%s</sub></td>\n' \
                "$img" "$img" "$thumb_width" "$name"
            count=$((count + 1))
        done < <(find "$dir" -maxdepth 1 -type f \( "${ext_args[@]}" \) -print0 | sort -z)
        echo "</tr>"
        echo "</table>"
    done
} > "$output"

echo "Generated $output: $total image(s) across ${#dirs[@]} folder(s)."
